// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aquanet.message.proto

#ifndef PROTOBUF_INCLUDED_aquanet_2emessage_2eproto
#define PROTOBUF_INCLUDED_aquanet_2emessage_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "dccl/option_extensions.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_aquanet_2emessage_2eproto 

namespace protobuf_aquanet_2emessage_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_aquanet_2emessage_2eproto
class AquanetMessage;
class AquanetMessageDefaultTypeInternal;
extern AquanetMessageDefaultTypeInternal _AquanetMessage_default_instance_;
namespace google {
namespace protobuf {
template<> ::AquanetMessage* Arena::CreateMaybeMessage<::AquanetMessage>(Arena*);
}  // namespace protobuf
}  // namespace google

enum AquanetMessage_VehicleClass {
  AquanetMessage_VehicleClass_AUV = 1,
  AquanetMessage_VehicleClass_USV = 2,
  AquanetMessage_VehicleClass_SHIP = 3
};
bool AquanetMessage_VehicleClass_IsValid(int value);
const AquanetMessage_VehicleClass AquanetMessage_VehicleClass_VehicleClass_MIN = AquanetMessage_VehicleClass_AUV;
const AquanetMessage_VehicleClass AquanetMessage_VehicleClass_VehicleClass_MAX = AquanetMessage_VehicleClass_SHIP;
const int AquanetMessage_VehicleClass_VehicleClass_ARRAYSIZE = AquanetMessage_VehicleClass_VehicleClass_MAX + 1;

const ::google::protobuf::EnumDescriptor* AquanetMessage_VehicleClass_descriptor();
inline const ::std::string& AquanetMessage_VehicleClass_Name(AquanetMessage_VehicleClass value) {
  return ::google::protobuf::internal::NameOfEnum(
    AquanetMessage_VehicleClass_descriptor(), value);
}
inline bool AquanetMessage_VehicleClass_Parse(
    const ::std::string& name, AquanetMessage_VehicleClass* value) {
  return ::google::protobuf::internal::ParseNamedEnum<AquanetMessage_VehicleClass>(
    AquanetMessage_VehicleClass_descriptor(), name, value);
}
// ===================================================================

class AquanetMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:AquanetMessage) */ {
 public:
  AquanetMessage();
  virtual ~AquanetMessage();

  AquanetMessage(const AquanetMessage& from);

  inline AquanetMessage& operator=(const AquanetMessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AquanetMessage(AquanetMessage&& from) noexcept
    : AquanetMessage() {
    *this = ::std::move(from);
  }

  inline AquanetMessage& operator=(AquanetMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AquanetMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AquanetMessage* internal_default_instance() {
    return reinterpret_cast<const AquanetMessage*>(
               &_AquanetMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(AquanetMessage* other);
  friend void swap(AquanetMessage& a, AquanetMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AquanetMessage* New() const final {
    return CreateMaybeMessage<AquanetMessage>(NULL);
  }

  AquanetMessage* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<AquanetMessage>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const AquanetMessage& from);
  void MergeFrom(const AquanetMessage& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AquanetMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef AquanetMessage_VehicleClass VehicleClass;
  static const VehicleClass AUV =
    AquanetMessage_VehicleClass_AUV;
  static const VehicleClass USV =
    AquanetMessage_VehicleClass_USV;
  static const VehicleClass SHIP =
    AquanetMessage_VehicleClass_SHIP;
  static inline bool VehicleClass_IsValid(int value) {
    return AquanetMessage_VehicleClass_IsValid(value);
  }
  static const VehicleClass VehicleClass_MIN =
    AquanetMessage_VehicleClass_VehicleClass_MIN;
  static const VehicleClass VehicleClass_MAX =
    AquanetMessage_VehicleClass_VehicleClass_MAX;
  static const int VehicleClass_ARRAYSIZE =
    AquanetMessage_VehicleClass_VehicleClass_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  VehicleClass_descriptor() {
    return AquanetMessage_VehicleClass_descriptor();
  }
  static inline const ::std::string& VehicleClass_Name(VehicleClass value) {
    return AquanetMessage_VehicleClass_Name(value);
  }
  static inline bool VehicleClass_Parse(const ::std::string& name,
      VehicleClass* value) {
    return AquanetMessage_VehicleClass_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional string body_message = 5 [(.dccl.field) = {
  bool has_body_message() const;
  void clear_body_message();
  static const int kBodyMessageFieldNumber = 5;
  const ::std::string& body_message() const;
  void set_body_message(const ::std::string& value);
  #if LANG_CXX11
  void set_body_message(::std::string&& value);
  #endif
  void set_body_message(const char* value);
  void set_body_message(const char* value, size_t size);
  ::std::string* mutable_body_message();
  ::std::string* release_body_message();
  void set_allocated_body_message(::std::string* body_message);

  // optional double x = 2 [(.dccl.field) = {
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 2;
  double x() const;
  void set_x(double value);

  // optional double y = 3 [(.dccl.field) = {
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 3;
  double y() const;
  void set_y(double value);

  // optional double z = 4 [(.dccl.field) = {
  bool has_z() const;
  void clear_z();
  static const int kZFieldNumber = 4;
  double z() const;
  void set_z(double value);

  // required uint32 ros_msg_id = 1 [(.dccl.field) = {
  bool has_ros_msg_id() const;
  void clear_ros_msg_id();
  static const int kRosMsgIdFieldNumber = 1;
  ::google::protobuf::uint32 ros_msg_id() const;
  void set_ros_msg_id(::google::protobuf::uint32 value);

  // optional bool battery_ok = 7;
  bool has_battery_ok() const;
  void clear_battery_ok();
  static const int kBatteryOkFieldNumber = 7;
  bool battery_ok() const;
  void set_battery_ok(bool value);

  // optional uint32 stream_id = 8 [(.dccl.field) = {
  bool has_stream_id() const;
  void clear_stream_id();
  static const int kStreamIdFieldNumber = 8;
  ::google::protobuf::uint32 stream_id() const;
  void set_stream_id(::google::protobuf::uint32 value);

  // optional .AquanetMessage.VehicleClass veh_class = 6;
  bool has_veh_class() const;
  void clear_veh_class();
  static const int kVehClassFieldNumber = 6;
  ::AquanetMessage_VehicleClass veh_class() const;
  void set_veh_class(::AquanetMessage_VehicleClass value);

  // @@protoc_insertion_point(class_scope:AquanetMessage)
 private:
  void set_has_ros_msg_id();
  void clear_has_ros_msg_id();
  void set_has_x();
  void clear_has_x();
  void set_has_y();
  void clear_has_y();
  void set_has_z();
  void clear_has_z();
  void set_has_body_message();
  void clear_has_body_message();
  void set_has_veh_class();
  void clear_has_veh_class();
  void set_has_battery_ok();
  void clear_has_battery_ok();
  void set_has_stream_id();
  void clear_has_stream_id();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr body_message_;
  double x_;
  double y_;
  double z_;
  ::google::protobuf::uint32 ros_msg_id_;
  bool battery_ok_;
  ::google::protobuf::uint32 stream_id_;
  int veh_class_;
  friend struct ::protobuf_aquanet_2emessage_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AquanetMessage

// required uint32 ros_msg_id = 1 [(.dccl.field) = {
inline bool AquanetMessage::has_ros_msg_id() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void AquanetMessage::set_has_ros_msg_id() {
  _has_bits_[0] |= 0x00000010u;
}
inline void AquanetMessage::clear_has_ros_msg_id() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void AquanetMessage::clear_ros_msg_id() {
  ros_msg_id_ = 0u;
  clear_has_ros_msg_id();
}
inline ::google::protobuf::uint32 AquanetMessage::ros_msg_id() const {
  // @@protoc_insertion_point(field_get:AquanetMessage.ros_msg_id)
  return ros_msg_id_;
}
inline void AquanetMessage::set_ros_msg_id(::google::protobuf::uint32 value) {
  set_has_ros_msg_id();
  ros_msg_id_ = value;
  // @@protoc_insertion_point(field_set:AquanetMessage.ros_msg_id)
}

// optional double x = 2 [(.dccl.field) = {
inline bool AquanetMessage::has_x() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AquanetMessage::set_has_x() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AquanetMessage::clear_has_x() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AquanetMessage::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline double AquanetMessage::x() const {
  // @@protoc_insertion_point(field_get:AquanetMessage.x)
  return x_;
}
inline void AquanetMessage::set_x(double value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:AquanetMessage.x)
}

// optional double y = 3 [(.dccl.field) = {
inline bool AquanetMessage::has_y() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void AquanetMessage::set_has_y() {
  _has_bits_[0] |= 0x00000004u;
}
inline void AquanetMessage::clear_has_y() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void AquanetMessage::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline double AquanetMessage::y() const {
  // @@protoc_insertion_point(field_get:AquanetMessage.y)
  return y_;
}
inline void AquanetMessage::set_y(double value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:AquanetMessage.y)
}

// optional double z = 4 [(.dccl.field) = {
inline bool AquanetMessage::has_z() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void AquanetMessage::set_has_z() {
  _has_bits_[0] |= 0x00000008u;
}
inline void AquanetMessage::clear_has_z() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void AquanetMessage::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline double AquanetMessage::z() const {
  // @@protoc_insertion_point(field_get:AquanetMessage.z)
  return z_;
}
inline void AquanetMessage::set_z(double value) {
  set_has_z();
  z_ = value;
  // @@protoc_insertion_point(field_set:AquanetMessage.z)
}

// optional string body_message = 5 [(.dccl.field) = {
inline bool AquanetMessage::has_body_message() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AquanetMessage::set_has_body_message() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AquanetMessage::clear_has_body_message() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AquanetMessage::clear_body_message() {
  body_message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_body_message();
}
inline const ::std::string& AquanetMessage::body_message() const {
  // @@protoc_insertion_point(field_get:AquanetMessage.body_message)
  return body_message_.GetNoArena();
}
inline void AquanetMessage::set_body_message(const ::std::string& value) {
  set_has_body_message();
  body_message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:AquanetMessage.body_message)
}
#if LANG_CXX11
inline void AquanetMessage::set_body_message(::std::string&& value) {
  set_has_body_message();
  body_message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:AquanetMessage.body_message)
}
#endif
inline void AquanetMessage::set_body_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_body_message();
  body_message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:AquanetMessage.body_message)
}
inline void AquanetMessage::set_body_message(const char* value, size_t size) {
  set_has_body_message();
  body_message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:AquanetMessage.body_message)
}
inline ::std::string* AquanetMessage::mutable_body_message() {
  set_has_body_message();
  // @@protoc_insertion_point(field_mutable:AquanetMessage.body_message)
  return body_message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AquanetMessage::release_body_message() {
  // @@protoc_insertion_point(field_release:AquanetMessage.body_message)
  if (!has_body_message()) {
    return NULL;
  }
  clear_has_body_message();
  return body_message_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AquanetMessage::set_allocated_body_message(::std::string* body_message) {
  if (body_message != NULL) {
    set_has_body_message();
  } else {
    clear_has_body_message();
  }
  body_message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), body_message);
  // @@protoc_insertion_point(field_set_allocated:AquanetMessage.body_message)
}

// optional .AquanetMessage.VehicleClass veh_class = 6;
inline bool AquanetMessage::has_veh_class() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void AquanetMessage::set_has_veh_class() {
  _has_bits_[0] |= 0x00000080u;
}
inline void AquanetMessage::clear_has_veh_class() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void AquanetMessage::clear_veh_class() {
  veh_class_ = 1;
  clear_has_veh_class();
}
inline ::AquanetMessage_VehicleClass AquanetMessage::veh_class() const {
  // @@protoc_insertion_point(field_get:AquanetMessage.veh_class)
  return static_cast< ::AquanetMessage_VehicleClass >(veh_class_);
}
inline void AquanetMessage::set_veh_class(::AquanetMessage_VehicleClass value) {
  assert(::AquanetMessage_VehicleClass_IsValid(value));
  set_has_veh_class();
  veh_class_ = value;
  // @@protoc_insertion_point(field_set:AquanetMessage.veh_class)
}

// optional bool battery_ok = 7;
inline bool AquanetMessage::has_battery_ok() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void AquanetMessage::set_has_battery_ok() {
  _has_bits_[0] |= 0x00000020u;
}
inline void AquanetMessage::clear_has_battery_ok() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void AquanetMessage::clear_battery_ok() {
  battery_ok_ = false;
  clear_has_battery_ok();
}
inline bool AquanetMessage::battery_ok() const {
  // @@protoc_insertion_point(field_get:AquanetMessage.battery_ok)
  return battery_ok_;
}
inline void AquanetMessage::set_battery_ok(bool value) {
  set_has_battery_ok();
  battery_ok_ = value;
  // @@protoc_insertion_point(field_set:AquanetMessage.battery_ok)
}

// optional uint32 stream_id = 8 [(.dccl.field) = {
inline bool AquanetMessage::has_stream_id() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void AquanetMessage::set_has_stream_id() {
  _has_bits_[0] |= 0x00000040u;
}
inline void AquanetMessage::clear_has_stream_id() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void AquanetMessage::clear_stream_id() {
  stream_id_ = 0u;
  clear_has_stream_id();
}
inline ::google::protobuf::uint32 AquanetMessage::stream_id() const {
  // @@protoc_insertion_point(field_get:AquanetMessage.stream_id)
  return stream_id_;
}
inline void AquanetMessage::set_stream_id(::google::protobuf::uint32 value) {
  set_has_stream_id();
  stream_id_ = value;
  // @@protoc_insertion_point(field_set:AquanetMessage.stream_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::AquanetMessage_VehicleClass> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::AquanetMessage_VehicleClass>() {
  return ::AquanetMessage_VehicleClass_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_aquanet_2emessage_2eproto
